"""Test-only arrangement adapter for state moved by R3.3c."""

_NAMES = {
    "_reset_retirement_admission_mirror": "reset_retirement_admission_mirror",
    "_track_session_side_task": "track_session_side_task",
    "_quiesce_session_side_tasks": "quiesce_session_side_tasks",
    "_terminal_retirement_disposition": "terminal_retirement_disposition",
    "_termination_admission_closed": "termination_admission_closed",
    "_retirement_admission_closed": "retirement_admission_closed",
    "activate_termination_admission_fence": "activate_termination_admission_fence",
    "_termination_quiescent": "termination_quiescent",
    "_wait_for_termination_quiescence": "wait_for_termination_quiescence",
    "_handle_heartbeat_intents": "handle_heartbeat_intents",
    "_session_parked": "session_parked",
    "_drain_suspend_session": "drain_suspend_session",
    "_start_pending_exact_drain_suspend_retry": "start_pending_exact_drain_suspend_retry",
    "_retry_pending_exact_drain_suspend": "retry_pending_exact_drain_suspend",
    "_deregister_before_exit": "deregister_before_exit",
    "_schedule_exit": "schedule_exit",
    "_boot_ws_watchdog": "boot_ws_watchdog",
    "_thread_status_watchdog": "thread_status_watchdog",
    "_start_watchdogs": "start_watchdogs",
    "_stop_watchdogs": "stop_watchdogs",
    "_stop_and_join_watchdogs": "stop_and_join_watchdogs",
    "_signal_ws_connected": "signal_ws_connected",
    "_exit_workspace_not_ready": "exit_workspace_not_ready",
    "_exit_grant_denied": "exit_grant_denied",
    "_exit_memory_unavailable": "exit_memory_unavailable",
    "_exit_duplicate_provision": "exit_duplicate_provision",
    "_exit_session_ended": "exit_session_ended",
    "_terminate_session": "terminate",
    "_dedicated_pod_owes_exit": "dedicated_pod_owes_exit",
    "_request_vm_retirement_actuator": "request_vm_retirement_actuator",
    "_settle_exact_retirement_after_quiescence": "settle_exact_retirement_after_quiescence",
    "_terminate_session_inner": "_terminate_inner",
    "_detach_session": "detach_session",
    "_loop_completion_handler": "loop_completion_handler",
    "_reconcile_retirement_begin_or_reopen_controls": "reconcile_retirement_begin_or_reopen_controls",
    "_begin_exact_session_retirement": "begin_retirement",
    "_runtime_admission_closed": "runtime_admission_closed",
    "_retirement_admission_identity": "retirement_admission_identity",
    "_retirement_admission_disposition": "retirement_admission_disposition",
    "_retirement_admission_token": "retirement_admission_token",
    "_retirement_admission_permanent": "retirement_admission_permanent",
    "_pending_drain_suspend": "pending_drain_suspend",
    "_pending_drain_suspend_retry_task": "pending_drain_suspend_retry_task",
    "_pending_exit_task": "pending_exit_task",
    "_drain_intent_handled": "drain_intent_handled",
    "_drain_deferred_logged": "drain_deferred_logged",
    "_termination_admission_fenced": "termination_admission_fenced",
    "_termination_fence_reason": "termination_fence_reason",
    "_ws_connected_event": "ws_connected_event",
    "_watchdog_tasks": "watchdog_tasks",
    "_terminating": "terminating",
    "_termination_task": "termination_task",
    "_sessions_served": "sessions_served",
    "_max_sessions_per_process": "max_sessions_per_process",
    "_session_side_tasks": "session_side_tasks",
    "_TERMINATION_SENTINEL_PATH": "termination_sentinel_path",
    "_TERMINATION_QUEUE_SENTINEL": "termination_queue_sentinel",
    "_session_boot_ws_timeout_s": "session_boot_ws_timeout_s",
    "_thread_status_poll_s": "thread_status_poll_s",
}


def termination_target(module, name):
    if name in _NAMES and hasattr(module, "_session_termination"):
        return module._session_termination, _NAMES[name]
    return module, name
